---
- hosts: all
  vars_files:
    - vars/image_url.yml
    - vars/user_settings.yml
  roles:
    - role: flash
      tags:
      - noetic
      - eloquent
      - foxy
    # - role: setup
    #   tags:
    #   - noetic
    #   - eloquent
    #   - foxy

    # - name: copy install script for ROS1
    #   copy:
    #     src: "{{ ansible_env.PWD }}/scripts/register_ros_keys.sh"
    #     dest: /media/{{ ansible_user }}/writable/home/register_ros_keys.sh
    #     mode: a+x
    #     follow: yes
    #   become: yes
    #   tags:
    #     - noetic
    # - name: copy install script for ROS2
    #   copy:
    #     src: "{{ ansible_env.PWD }}/scripts/register_ros2_keys.sh"
    #     dest: /media/{{ ansible_user }}/writable/home/register_ros2_keys.sh
    #     mode: a+x
    #     follow: yes
    #   become: yes
    #   tags:
    #     - eloquent
    #     - foxy
    # - name: register ros1 keys
    #   shell: chroot /media/{{ ansible_user }}/writable /bin/bash home/register_ros_keys.sh
    #   become: yes
    #   tags:
    #     - noetic
    # - name: register ros2 keys
    #   shell: chroot /media/{{ ansible_user }}/writable /bin/bash home/register_ros2_keys.sh
    #   become: yes
    #   tags:
    #     - eloquent
    #     - foxy