---
- hosts: all
  vars_files:
    - vars/image_url.yml
    - vars/user_settings.yml
  roles:
    # - role: flash
    #   tags: always
    # - role: setup
    - role: install_driver
      tags: always