---
- hosts: all
  vars_files:
    - vars/image_url.yml
    - vars/user_settings.yml
  tasks:
    - name: Install rpi-imager
      snap:
        name:
          - rpi-imager
      become: yes
    - name: download image
      get_url:
        url: "{{ ubuntu_20_04.image_url }}"
        checksum: sha256:"{{ ubuntu_20_04.sha256sum }}"
        dest: /home/{{ ansible_user }}/Downloads/{{ ubuntu_20_04.filename }}
#    - name: flash image {{ sd_device }}
#      shell: rpi-imager --cli /home/{{ ansible_user }}/Downloads/{{ ubuntu_20_04.filename }} {{ sd_device }}
    - name: install qemu
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      vars:
        packages:
          - qemu-user-static
      become: yes
    - name: remout {{ sd_device }}
      shell: mount -o remount,rw {{ sd_device }}2 /media/{{ ansible_user }}/writable/
      become: true
    - name: copy resolv.conf to sd card {{ sd_device }}
      copy:
        src: /etc/resolv.conf
        dest: /media/{{ ansible_user }}/writable/etc/resolv.conf
        mode: a+x
        follow: yes
      become: yes
    - name: copy qemu-user-static binary to sd card {{ sd_device }}
      copy:
        src: /usr/bin/qemu-arm-static
        dest: /media/{{ ansible_user }}/writable/usr/bin/qemu-arm-static
        mode: a+x
        follow: yes
    - name: delete user {{ turtlebot3_username }} for turtlebot3
      shell: chroot /media/ouxtpolaris/writable/ userdel {{ turtlebot3_username }}
      become: yes
      ignore_errors: yes
    - name: add user {{ turtlebot3_username }} for turtlebot3
      shell: chroot /media/{{ ansible_user }}/writable/ useradd -m {{ turtlebot3_username }} -g root -p {{ turtlebot3_password }}
      become: yes
    - name: copy ROS install script for noetic
      copy:
        src: "{{ ansible_env.PWD }}/scripts/install_noetic.sh"
        dest: /media/{{ ansible_user }}/writable/home/install_ros.sh
        mode: a+x
        follow: yes
      become: yes