---
- name: copy resolv.conf to sd card {{ sd_device }}
  copy:
    src: /etc/resolv.conf
    dest: /media/{{ ansible_user }}/writable/etc/resolv.conf
    mode: a+x
    follow: yes
  become: yes
- name: copy qemu-user-static binary to sd card {{ sd_device }}
  copy:
    src: /usr/bin/qemu-arm-static
    dest: /media/{{ ansible_user }}/writable/usr/bin/qemu-arm-static
    mode: a+x
    follow: yes
  become: yes
- name: delete user {{ turtlebot3_username }} for turtlebot3
  shell: chroot /media/ouxtpolaris/writable/ userdel {{ turtlebot3_username }}
  become: yes
  ignore_errors: yes
- name: add user {{ turtlebot3_username }} for turtlebot3
  shell: chroot /media/{{ ansible_user }}/writable/ useradd -m {{ turtlebot3_username }} -g root -p {{ turtlebot3_password }}
  become: yes
- name: copy install script for ROS1
  copy:
    src: "{{ ansible_env.PWD }}/scripts/register_ros_keys.sh"
    dest: /media/{{ ansible_user }}/writable/home/register_ros_keys.sh
    mode: a+x
    follow: yes
  become: yes
  tags:
    - noetic
- name: copy install script for ROS2
  copy:
    src: "{{ ansible_env.PWD }}/scripts/register_ros2_keys.sh"
    dest: /media/{{ ansible_user }}/writable/home/register_ros2_keys.sh
    mode: a+x
    follow: yes
  become: yes
  tags:
    - eloquent
    - foxy
- name: run install script for ROS1
  shell: chroot /media/{{ ansible_user }}/writable/ /bin/bash /home/register_ros_keys.sh
  tags:
    - noetic
  become: yes
- name: run install script for ROS2
  shell: chroot /media/{{ ansible_user }}/writable /home/register_ros2_keys.sh
  tags:
    - eloquent
    - foxy
  become: yes
- name: install ROS (noetic)
  shell: chroot /media/{{ ansible_user }}/writable apt install ros-noetic-ros-base
  tags:
    - noetic
  become: yes
- name: install ROS2 (eloquent)
  shell: chroot /media/{{ ansible_user }}/writable apt install ros-eloquent-ros-base
  tags:
    - eloquent
  become: yes
- name: install ROS2 (foxy)
  shell: chroot /media/{{ ansible_user }}/writable apt install ros-foxy-ros-base
  tags:
    - foxy
  become: yes