# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    # Display the VirtualBox GUI when booting the machine
    v.gui = false

    # Customize the amount of memory on the VM:
    v.memory = "2048"
    v.cpus   = "2"
  end
  
  config.vm.define "turtlebot3_setup.vagrant.local"
  config.vm.provision "ansible" do |ansible|
    ansible.limit          = "turtlebot3_setup.vagrant.local"
    ansible.playbook       = "../turtlebot3_setup-playbook.yml"
    ansible.verbose        = false
  end
end

