name: run_playbook

on:
  schedule:
  - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_playbook:
    name: run_playbook
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
    - name: lsblk
      run: lsblk
    - name: mknod
      run: mknod /dev/loop3 b 7 3
    - name: chmod
      run: chmod a+x /dev/loop3
    - name: make empty disk image
      run: touch disk.img
    - name: flash empty disk image
      run: dd if=/dev/zero of=disk.img bs=32M count=250
    - name: losetup -f
      run: losetup -f
    - name: setup loopback
      run: losetup /dev/loop3 disk.img
    - name: lsblk
      run: lsblk