name: run_playbook

on:
  schedule:
  - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_playbook:
    name: run_playbook
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v2-beta
    - name: lsblk
      run: lsblk
    - name: make mount directory
      run: mkdir virtual_device
    - name: mount virtual_device
      run: mount /dev/sda virtual_device